name: Build, Push, Deploy.

on:
  push:
    branches: [master]

jobs:
  build_and_push:
    name: Push docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          ecr: auto
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_ACCESS_TOKEN}}

      - name: Extract metadata (labels, tags,etc. ) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jambhaleanuj32/instagram-ai-caption-backend
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: jambhaleanuj32/instagram-ai-caption-backend:latest
          labels: ${{ steps.meta.outputs.labels }}
